frame_budget:
  duration: "10ms"
  method: "Busy"
kernels:
  - name: "strided_pythagorus"
    blocks: 32
    threads: 256
    stream: "stream1"
    args:
      - type: "double*"
        name: "a"
      - type: "double*"
        name: "b"
      - type: "double*"
        name: "c"
      - type: "int"
        name: "n"
  - name: "strided_reduce_sum"
    blocks: 32
    threads: 256
    shared_memory_bytes: 2048
    stream: "stream2"
    args:
      - type: "double*"
        name: "d"
      - type: "float*"
        name: "d_sum"
      - type: "int"
        name: "n"
  - name: "cellular_vec_add"
    blocks: 16384
    threads: 256
    stream: "stream3"
    args:
      - type: "double*"
        name: "e"
      - type: "double*"
        name: "f"
      - type: "double*"
        name: "g"
      - type: "int"
        name: "n"
  - name: "grayscale_filter"
    blocks: 16384
    threads: 256
    stream: "stream4"
    args:
      - type: "unsigned char*"
        name: "rgb"
      - type: "unsigned char*"
        name: "gray"
      - type: "int"
        name: "width"
      - type: "int"
        name: "height"
  - name: "convolution_2d"
    blocks: 4041
    threads: 256
    stream: "stream5"
    args:
      - type: "float*"
        name: "conv_input"
      - type: "float*"
        name: "conv_kernel"
      - type: "float*"
        name: "conv_output"
      - type: "int"
        name: "input_width"
      - type: "int"
        name: "input_height"
      - type: "int"
        name: "kernel_width"
      - type: "int"
        name: "kernel_height"
  - name: "sdf_cuda_kernel"
    blocks: 512
    threads: 256
    stream: "stream6"
    args:
      - type: "float*"
        name: "phi"
      - type: "int32_t*"
        name: "faces"
      - type: "float*"
        name: "vertices"
      - type: "int"
        name: "batch_size"
      - type: "int"
        name: "num_faces"
      - type: "int"
        name: "num_vertices"
      - type: "int"
        name: "grid_size"
setup:
  name: "setup"
  args:
    - type: "double*"
      name: "a"
    - type: "double*"
      name: "b"
    - type: "double*"
      name: "c"
    - type: "double*"
      name: "d"
    - type: "float*"
      name: "d_sum"
    - type: "double*"
      name: "e"
    - type: "double*"
      name: "f"
    - type: "double*"
      name: "g"
    - type: "int"
      name: "n"
    - type: "unsigned char*"
      name: "rgb"
    - type: "unsigned char*"
      name: "gray"
    - type: "int"
      name: "width"
    - type: "int"
      name: "height"
    - type: "float*"
      name: "conv_input"
    - type: "float*"
      name: "conv_kernel"
    - type: "float*"
      name: "conv_output"
    - type: "int"
      name: "input_width"
    - type: "int"
      name: "input_height"
    - type: "int"
      name: "kernel_width"
    - type: "int"
      name: "kernel_height"
    - type: "float*"
      name: "phi"
    - type: "int32_t*"
      name: "faces"
    - type: "float*"
      name: "vertices"
    - type: "int"
      name: "batch_size"
    - type: "int"
      name: "num_faces"
    - type: "int"
      name: "num_vertices"
    - type: "int"
      name: "grid_size"
